#19 elementShouldBeVisible Should be public
ONSdigital/dp-component-test pull request #20
Opened 2022-02-18 18:34 UTC by joegasewicz

### What
adds 2 public functions `ElementShouldBeVisibleNoPattern` & `ElementShouldBeVisible`
Describe what you have changed and why.

### How to review
either visually or by pulling down the branch, link to a front end app with 
```
replace (
	github.com/ONSdigital/dp-component-test => /<PATH_TO_YOUR_LOCAL_REPO>/dp-component-test
)
```
Run component tests with the following added steps:

`ctx.Step(`^And breadcrumbs should be visible  if "([^"]*) exists"`, uiFeature.ElementShouldBeVisible)`
`ctx.Step(`^I should see breadcrumbs`, uiFeature.ElementShouldBeVisibleNoPattern("nav.ons-breadcrumb"))`

Describe the steps required to test the changes.
see above
### Who can review
team 404

Describe who worked on the changes, so that other people can review.
Myself

2022-03-03 17:01 UTC, cookel2 requested changes

2022-03-03 17:04 UTC, cookel2 commented on ui_feature.go
> +func (f *UIFeature) RunWithTimeOut(ctx *context.Context, timeout time.Duration, tasks chromedp.Tasks) chromedp.ActionFunc {
The ctx parameter is not being used
```suggestion
func (f *UIFeature) RunWithTimeOut(timeout time.Duration, tasks chromedp.Tasks) chromedp.ActionFunc {
```

2022-03-03 17:15 UTC, cookel2 commented on ui_feature.go
> +			f.RunWithTimeOut(&f.Chrome.Ctx, f.WaitTimeOut, chromedp.Tasks{
If the RunWithTimeOut signature is changed then this will need to be changed too.

2022-03-04 09:03 UTC, cookel2 commented
Sorry @joegasewicz I just realised that you asked for this to be reviewed by team 404. So I will approve it after someone from there has done.

2022-03-04 09:25 UTC, joegasewicz commented
@cookel2 You can review this should review this as it is agnostic in terms of teams using this code. I've updated the `Who can review` section to `anyone` thank you

2022-03-04 10:47 UTC, cookel2 commented on STEP_DEFINITIONS.md
> +| the page should contain "KEY" with list element text [LIST] at INT depth
The 'What it does'  looks good but the 'Scenario Position' column is still empty.

2022-03-04 10:50 UTC, cookel2 requested changes
Just one more little change please.

2022-03-04 11:15 UTC, cookel2 approved these changes
looks good to me

2022-03-04 11:25 UTC, merged