Update mongodb-in-memory library
ONSdigital/dp-component-test pull request #27
Opened 2022-11-11 15:22 UTC by PatrickConnollyONS

### What

Update version of golang and mongodb-in-memory lib, and fix audit issue

### How to review

Review code

### Who can review

Anyone

2022-11-16 13:32 UTC, ChrysmOre submitted a review, later dismissed

2022-11-22 15:37 UTC, cookel2 requested changes

2022-11-22 15:37 UTC, cookel2 commented on go.mod
> +	github.com/ONSdigital/dp-mongodb-in-memory v1.5.0
Some of the other lines in this require block need to be deleted as they contain unused dependencies (lines 8, 9, and 13): 
```
github.com/chromedp/cdproto v0.0.0-20211126220118-81fa0469ad77
github.com/chromedp/chromedp v0.7.6
github.com/smartystreets/goconvey v1.7.2
```

2022-11-22 15:37 UTC, cookel2 commented on mongo_feature.go
> +		err         error
This err is used in line 61 but GoLand complains that it is not of type 'any':
```
Cannot use 'err' (type error) as the type any
```

2022-11-22 17:15 UTC, cookel2 approved these changes

2022-11-22 17:26 UTC, merged